# Generated by Django 5.1 on 2024-09-04 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("probability", models.FloatField()),
                ("status", models.BooleanField(default=True)),
                ("s_weight", models.FloatField(blank=True, null=True)),
                ("a_weight", models.FloatField(blank=True, null=True)),
                ("b_weight", models.FloatField(blank=True, null=True)),
                ("c_weight", models.FloatField(blank=True, null=True)),
                ("mean", models.FloatField(default=1.75)),
                ("standard_deviation", models.FloatField(default=0.625)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("user_name", models.CharField(max_length=255)),
                ("coins", models.IntegerField(default=0)),
                ("diamonds", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("current_experience", models.IntegerField(default=0)),
                ("experience_for_next_level", models.IntegerField(default=100)),
                ("rod_type", models.CharField(default="basic", max_length=255)),
                ("fish_inventory", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="FishCatched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                ("rarity_level", models.CharField(max_length=50)),
                ("image_url", models.URLField()),
                ("caught_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.FloatField(default=1)),
                (
                    "fish_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishing_app.fish",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishing_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fish_catched", models.ManyToManyField(to="fishing_app.fishcatched")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishing_app.user",
                    ),
                ),
            ],
        ),
    ]
