# Generated by Django 5.1 on 2024-09-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fishing_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                (
                    "coins",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "diamonds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShoppedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=255)),
                ("product_type", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
